import { TrendCard } from "@/lib/types";

// MVP：手动写入的趋势卡（不抓取网站内容，不搬运版权文章/图片）
export const trendSeedData: TrendCard[] = [
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d01",
    trend_name: "西村都市风 - West Village Style",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "精致日常基础款，带一点学院与城市漫步感。线条干净、中性色为主，叠穿自然不费力。",
    style_tags: ["work", "casual", "formal"],
    color_tags: ["cream", "beige", "navy", "black", "white"],
    top_keywords: ["button-down", "knit", "stripe", "cardigan"],
    bottom_keywords: ["straight pants", "denim", "long skirt"],
    occasion_tags: ["work", "weekend"],
    season_tags: ["spring", "fall", "all-season"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d02",
    trend_name: "净透夏日风 - Clean Girl Summer",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "极简、清爽、轻盈。版型简单、明亮中性色、面料透气轻薄。",
    style_tags: ["casual", "work"],
    color_tags: ["white", "cream", "beige"],
    top_keywords: ["tank", "tee", "fitted", "minimal"],
    bottom_keywords: ["linen", "wide-leg", "long skirt", "shorts"],
    occasion_tags: ["weekend", "date", "travel"],
    season_tags: ["summer"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d03",
    trend_name: "汉江极简风 - Korean Minimal",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "松弛比例与低饱和色调。干净廓形里带一点点街头感。",
    style_tags: ["casual", "streetwear"],
    color_tags: ["gray", "navy", "black", "white"],
    top_keywords: ["oversized tee", "shirt", "light knit"],
    bottom_keywords: ["straight pants", "wide-leg", "denim"],
    occasion_tags: ["weekend", "travel"],
    season_tags: ["spring", "fall"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d04",
    trend_name: "巴黎慵懒风 - French Casual",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "不费力的精致：条纹、牛仔、克制的中性色，简单单品也能很有气质。",
    style_tags: ["casual", "work"],
    color_tags: ["navy", "white", "cream", "blue"],
    top_keywords: ["striped tee", "button-down", "cardigan"],
    bottom_keywords: ["denim", "straight pants", "long skirt"],
    occasion_tags: ["weekend", "work", "date"],
    season_tags: ["spring", "summer", "fall"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d05",
    trend_name: "浅色老钱风 - Old Money Light Summer",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "低调奢感配合透气面料：轻薄针织、亚麻下装、柔和中性色。",
    style_tags: ["formal", "work", "casual"],
    color_tags: ["cream", "beige", "white", "navy"],
    top_keywords: ["polo", "light knit", "shirt"],
    bottom_keywords: ["linen", "tailored pants", "long skirt"],
    occasion_tags: ["work", "travel", "date"],
    season_tags: ["summer"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d06",
    trend_name: "丹宁叠穿风 - Denim-on-Denim",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "强势但经典：牛仔上装叠牛仔下装。颜色尽量接近，整体更像套装更利落。",
    style_tags: ["streetwear", "casual"],
    color_tags: ["blue", "navy"],
    top_keywords: ["denim jacket", "denim shirt"],
    bottom_keywords: ["denim", "straight pants"],
    occasion_tags: ["weekend"],
    season_tags: ["fall", "spring"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d07",
    trend_name: "白衫长裙风 - White Top + Long Skirt",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "对比简单、线条干净。明亮上装平衡优雅长裙，很显气质。",
    style_tags: ["casual", "party", "work"],
    color_tags: ["white", "cream", "beige", "black"],
    top_keywords: ["white tee", "tank", "shirt"],
    bottom_keywords: ["long skirt", "midi skirt"],
    occasion_tags: ["date", "weekend", "work"],
    season_tags: ["spring", "summer"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d08",
    trend_name: "廓形衬衫风 - Oversized Shirt + Straight Pants",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "适合大多数身材的可靠廓形：上松下直，干净利落不挑人。",
    style_tags: ["work", "casual"],
    color_tags: ["white", "blue", "beige", "gray"],
    top_keywords: ["oversized shirt", "button-down"],
    bottom_keywords: ["straight pants", "tailored pants"],
    occasion_tags: ["work", "travel"],
    season_tags: ["spring", "fall", "all-season"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d09",
    trend_name: "纯粹深灰风 - Monochrome Grey",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "冷静现代的同色系灰。用不同材质做层次，看起来更“有搭配”。",
    style_tags: ["work", "casual"],
    color_tags: ["gray", "black", "white"],
    top_keywords: ["sweater", "tee", "minimal"],
    bottom_keywords: ["straight pants", "wide-leg"],
    occasion_tags: ["work", "weekend"],
    season_tags: ["fall", "winter"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d10",
    trend_name: "街头漫步风 - City Walk Casual",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "以舒适为先的城市日常：简单上装 + 实用下装，带一点轻运动感。",
    style_tags: ["casual", "sporty"],
    color_tags: ["white", "black", "navy", "gray"],
    top_keywords: ["tee", "hoodie", "light jacket"],
    bottom_keywords: ["denim", "straight pants", "shorts"],
    occasion_tags: ["weekend", "travel"],
    season_tags: ["spring", "summer", "fall"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d11",
    trend_name: "低调静奢风 - Quiet Luxury Basics",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "高质基础款 + 克制配色 + 合身剪裁。低调但看起来很“贵”。",
    style_tags: ["formal", "work"],
    color_tags: ["cream", "beige", "navy", "black"],
    top_keywords: ["knit", "shirt", "clean"],
    bottom_keywords: ["tailored pants", "straight pants"],
    occasion_tags: ["work"],
    season_tags: ["all-season"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d12",
    trend_name: "清爽亚麻风 - Summer Linen Look",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "透气亚麻质感配浅色中性色。清爽、轻盈、耐热。",
    style_tags: ["casual", "work"],
    color_tags: ["beige", "cream", "white"],
    top_keywords: ["linen shirt", "tank", "tee"],
    bottom_keywords: ["linen pants", "wide-leg", "shorts"],
    occasion_tags: ["travel", "weekend"],
    season_tags: ["summer"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d13",
    trend_name: "芭蕾清简风 - Ballet Flat Minimalism",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "柔和的极简感：干净上装搭配优雅、简单的下装，气质温柔。",
    style_tags: ["casual", "party", "work"],
    color_tags: ["black", "white", "cream", "pink"],
    top_keywords: ["minimal", "fitted", "cardigan"],
    bottom_keywords: ["long skirt", "straight pants"],
    occasion_tags: ["date", "work"],
    season_tags: ["spring", "fall"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d14",
    trend_name: "动感休闲风 - Sporty Casual",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "运动休闲混搭：宽松上装 + 简洁下装，带一点运动能量。",
    style_tags: ["sporty", "casual"],
    color_tags: ["gray", "black", "white", "navy"],
    top_keywords: ["hoodie", "tee", "zip jacket"],
    bottom_keywords: ["shorts", "straight pants"],
    occasion_tags: ["sport", "weekend"],
    season_tags: ["all-season"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d15",
    trend_name: "柔和叠穿风 - Soft Neutral Layers",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "适合叠穿的中性色，柔和对比。干净、温柔、不会显沉重。",
    style_tags: ["casual", "work"],
    color_tags: ["cream", "beige", "brown", "gray"],
    top_keywords: ["cardigan", "knit", "light jacket"],
    bottom_keywords: ["straight pants", "denim"],
    occasion_tags: ["work", "weekend"],
    season_tags: ["fall", "winter"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d16",
    trend_name: "原宿清冷风 - Tokyo Minimal Street",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "极简廓形带一点街头锋利感：深色中性、干净线条、刻意的松量。",
    style_tags: ["streetwear", "casual"],
    color_tags: ["black", "gray", "navy"],
    top_keywords: ["oversized", "jacket", "tee"],
    bottom_keywords: ["wide-leg", "straight pants"],
    occasion_tags: ["weekend", "travel"],
    season_tags: ["fall", "spring"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d17",
    trend_name: "港式雅致风 - Hong Kong Weekend",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "针对潮湿闷热的轻薄穿搭：简单上装 + 透气下装，行动更自在。",
    style_tags: ["casual"],
    color_tags: ["white", "cream", "blue", "gray"],
    top_keywords: ["tee", "light shirt", "tank"],
    bottom_keywords: ["shorts", "linen", "straight pants"],
    occasion_tags: ["weekend", "travel"],
    season_tags: ["summer"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d18",
    trend_name: "职场通勤风 - Office Smart Casual",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "上班友好但不死板：干净上装 + 合身下装，配色平衡。",
    style_tags: ["work", "formal"],
    color_tags: ["navy", "black", "white", "beige"],
    top_keywords: ["shirt", "knit", "polo"],
    bottom_keywords: ["tailored pants", "straight pants"],
    occasion_tags: ["work"],
    season_tags: ["all-season"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d19",
    trend_name: "约会简约风 - Date Night Minimal",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "极简但有心机：干净线条里只保留一个亮点（材质/廓形/对比）。",
    style_tags: ["party", "formal"],
    color_tags: ["black", "red", "white", "cream"],
    top_keywords: ["fitted", "clean", "dark"],
    bottom_keywords: ["long skirt", "tailored pants"],
    occasion_tags: ["date", "party"],
    season_tags: ["all-season"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2c9a2f9d-7f2c-4d6c-9f14-5a2d0d7f2d20",
    trend_name: "随性探店风 - Weekend Coffee Run",
    source_name: null,
    source_url: null,
    published_date: null,
    summary: "简单、舒服、又有点可爱：上装+下装的周末“制服”组合。",
    style_tags: ["casual"],
    color_tags: ["cream", "gray", "navy", "white"],
    top_keywords: ["tee", "sweatshirt", "light jacket"],
    bottom_keywords: ["denim", "straight pants", "shorts"],
    occasion_tags: ["weekend"],
    season_tags: ["all-season"],
    created_at: new Date().toISOString(),
  },
];
